import { TABLES } from './database.enums';

export const tablesSchemas = [
  {
    tableName: `${TABLES.users}`,
    query: `
      CREATE TABLE IF NOT EXISTS ${TABLES.users} (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          surname VARCHAR(255) NOT NULL,
          email VARCHAR(255) NOT NULL UNIQUE,
          password VARCHAR(255) NOT NULL,
          phone VARCHAR(255) NOT NULL,
          age INT NOT NULL,
          country VARCHAR(255) NOT NULL,
          district VARCHAR(255) NOT NULL,
          role VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
          )
          `,
    unRecoveableHashColumns: ['password'],
    dummyData: [
      {
        name: 'Mach',
        surname: 'Ironman',
        email: 'Mach.Ironman@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 42,
        country: 'USA',
        district: 'PA',
        role: 'admin',
      },
      {
        name: 'Jhon',
        surname: 'Leen',
        email: 'Jhon.Leen@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 60,
        country: 'Mexico',
        district: 'NY',
        role: 'user',
      },
      {
        name: 'Marcus',
        surname: 'Leon',
        email: 'Marcus.Leon@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 50,
        country: 'Spain',
        district: 'NC',
        role: 'user',
      },
      {
        name: 'Chris',
        surname: 'Davis',
        email: 'chris.davis3@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 26,
        country: 'Brazil',
        district: 'CA',
        role: 'user',
      },
      {
        name: 'Alex',
        surname: 'Brown',
        email: 'alex.brown4@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 21,
        country: 'France',
        district: 'TX',
        role: 'user',
      },
      {
        name: 'Alex',
        surname: 'Garcia',
        email: 'alex.garcia5@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 24,
        country: 'Australia',
        district: 'FL',
        role: 'user',
      },
      {
        name: 'Alice',
        surname: 'Garcia',
        email: 'alice.garcia6@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 47,
        country: 'USA',
        district: 'GA',
        role: 'user',
      },
      {
        name: 'Bob',
        surname: 'Miller',
        email: 'bob.miller7@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 19,
        country: 'UK',
        district: 'IL',
        role: 'user',
      },
      {
        name: 'Bob',
        surname: 'Garcia',
        email: 'bob.garcia8@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 38,
        country: 'Spain',
        district: 'FL',
        role: 'user',
      },
      {
        name: 'John',
        surname: 'Miller',
        email: 'john.miller9@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 39,
        country: 'UK',
        district: 'GA',
        role: 'user',
      },
      {
        name: 'Jane',
        surname: 'Williams',
        email: 'jane.williams10@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 20,
        country: 'Germany',
        district: 'OH',
        role: 'user',
      },
      {
        name: 'Chris',
        surname: 'Miller',
        email: 'chris.miller11@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 46,
        country: 'Canada',
        district: 'PA',
        role: 'user',
      },
      {
        name: 'Alice',
        surname: 'Williams',
        email: 'alice.williams12@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 37,
        country: 'USA',
        district: 'TX',
        role: 'user',
      },
      {
        name: 'Bob',
        surname: 'Davis',
        email: 'bob.davis13@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 34,
        country: 'Italy',
        district: 'CA',
        role: 'user',
      },
      {
        name: 'Chris',
        surname: 'Garcia',
        email: 'chris.garcia14@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 47,
        country: 'Mexico',
        district: 'TX',
        role: 'user',
      },
      {
        name: 'Kate',
        surname: 'Brown',
        email: 'kate.brown15@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 34,
        country: 'Germany',
        district: 'CA',
        role: 'user',
      },
      {
        name: 'Emily',
        surname: 'Garcia',
        email: 'emily.garcia16@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 33,
        country: 'Spain',
        district: 'NY',
        role: 'user',
      },
      {
        name: 'Alice',
        surname: 'Brown',
        email: 'alice.brown17@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 49,
        country: 'Mexico',
        district: 'FL',
        role: 'user',
      },
      {
        name: 'Alex',
        surname: 'Johnson',
        email: 'alex.johnson18@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 51,
        country: 'France',
        district: 'NC',
        role: 'user',
      },
      {
        name: 'Kate',
        surname: 'Williams',
        email: 'kate.williams19@localhost.com',
        password: 'P@ssw0rd',
        phone: '123-456-7890',
        age: 23,
        country: 'Canada',
        district: 'FL',
        role: 'user',
      },
    ],
  },
];
